language: node_js  #设置语言

node_js: stable  #设置相应的版本

before_install:
  - git config user.name "zianeCui"  #修改name
  - git config user.email "zianecui@gmail.com"  #修改email
  - npm install -g hexo-cli

install:
  - npm install  #安装hexo及插件

script:
  - hexo cl  #清除
  - hexo g  #生成

after_script:
  - cd ./public
  - git init
  - git config user.name "zianeCui"  #修改name
  - git config user.email "zianecui@gmail.com"  #修改email
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称

after_success:
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --quiet --force https://$REPO_TOKEN@github.com/ZianeCui/ZianeCui.github.io.git  master:master